from django.db import models

class Order(BaseModel):
    user = models.ForeignKey(user)
    sender_comapny_name = models.CharField(max_length=256, null=True, blank=True)
    receiver_comapny_name = models.CharField(max_length=256, null=True, blank=True)
    sender_name = models.CharField(max_length=256, null=True, blank=True)
    receiver_name = models.CharField(max_length=256, null=True, blank=True)
    sender_email = models.CharField(max_length=256, null=True, blank=True)
    receiver_email = models.CharField(max_length=256, null=True, blank=True)
    shipment_type = models.CharField(max_length=256, null=True, blank=True)
    sender_contact_number = models.CharField(max_length=20, null=True, blank=True)
    receiver_contact_number = models.CharField(max_length=256, null=True, blank=True)
    pickup_building_type = models.CharField(max_length=256, null=True, blank=True)
    pickup_elevator = models.CharField(max_length=256, null=True, blank=True)
    pickup_floor = models.CharField(max_length=256, null=True, blank=True)
    pickup_person = models.CharField(max_length=256, null=True, blank=True)
    drop_building_type = models.CharField(max_length=256, null=True, blank=True)
    drop_elevator = models.CharField(max_length=256, null=True, blank=True)
    drop_floor = models.CharField(max_length=256, null=True, blank=True)
    drop_person = models.CharField(max_length=256, null=True, blank=True)
    pickup_landline_number = models.CharField(max_length=20, null=True, blank=True)
    pickupaddress = models.CharField(max_length=256, null=True, blank=True)
    dropoffaddress = models.CharField(max_length=256, null=True, blank=True)
    pickup_unit_number = models.CharField(max_length=256, null=True, blank=True)
    pickup_house_number = models.CharField(max_length=256, null=True, blank=True)
    pickup_street_name = models.CharField(max_length=256, null=True, blank=True)
    pickup_street_suff = models.CharField(max_length=256, null=True, blank=True)
    pickup_suburb = models.CharField(max_length=256, null=True, blank=True)
    pickup_state = models.CharField(max_length=256, null=True, blank=True)
    pickup_postcode = models.CharField(max_length=256, null=True, blank=True)
    pickup_country = models.CharField(max_length=256, null=True, blank=True)
    item_description = models.CharField(max_length=256, null=True, blank=True)
    item_quantity = models.CharField(max_length=256, null=True, blank=True)
    delivery_date = models.CharField(max_length=256, null=True, blank=True)
    pickup_special_inst = models.CharField(max_length=256, null=True, blank=True)
    dropoff_first_name = models.CharField(max_length=256, null=True, blank=True)
    dropoff_last_name = models.CharField(max_length=256, null=True, blank=True)
    dropoff_mob_number = models.CharField(max_length=256, null=True, blank=True)
    dropoff_landline_number = models.CharField(max_length=256, null=True, blank=True)
    dropoff_special_inst = models.CharField(max_length=256, null=True, blank=True)
    dropoff_unit_number = models.CharField(max_length=256, null=True, blank=True)
    dropoff_house_number = models.CharField(max_length=256, null=True, blank=True)
    dropoff_stree_name = models.CharField(max_length=256, null=True, blank=True)
    dropoff_street_suff = models.CharField(max_length=256, null=True, blank=True)
    dropoff_suburb = models.CharField(max_length=256, null=True, blank=True)
    dropoff_state = models.CharField(max_length=256, null=True, blank=True)
    dropoff_postcode = models.CharField(max_length=256, null=True, blank=True)
    dropoff_country = models.CharField(max_length=256, null=True, blank=True)
    parcel_height = models.CharField(max_length=256, null=True, blank=True)
    parcel_width = models.CharField(max_length=256, null=True, blank=True)
    parcel_lenght = models.CharField(max_length=256, null=True, blank=True)
    parcel_weight = models.CharField(max_length=256, null=True, blank=True)
    delivery_distance = models.CharField(max_length=256, null=True, blank=True)
    delivery_duration = models.CharField(max_length=256, null=True, blank=True)
    delivery_time_duration = models.IntegerField(default=2) # DEFAULT '2',
    delivery_time = models.CharField(max_length=256, null=True, blank=True)
    status = models.CharField(max_length=20, null=True, blank=True) # DEFAULT 'No',
    cancel_status = models.CharField(max_length=256, null=True, blank=True)
    pickup_lat = models.CharField(max_length=60, null=True, blank=True)
    pickup_long = models.CharField(max_length=60, null=True, blank=True)
    drop_off_location = models.PointField()
    receiver_country_code = models.CharField(max_length=256, null=True, blank=True)
    sender_country_code = models.CharField(max_length=256, null=True, blank=True)
    driver = models.ForeignKey(Driver)
    driver_delivery_cost = models.CharField(max_length=256, null=True, blank=True)
    signature_image = models.ImageField()
    signature_name = models.CharField(max_length=256, null=True, blank=True)
    received_user_image = models.ImageField()
    receiver = models.ForeignKey(User)
    delivery_status = models.PositiveSmallIntegerField(choices=) # '1 =pending 2 = confirmed, 3= canceled, 4= delivered,5=paid,6=picked,7=accepted,8=reportproblem',
    delivery_cost = models.FloatField(default=0)
    vehicle_type = models.CharField(max_length=100, null=True, blank=True)
    delivery_type = models.CharField(max_length=100, null=True, blank=True)
    shipment_delivery_type = models.CharField(max_length=256, null=True, blank=True)
    number_of_package = models.CharField(max_length=50, null=True, blank=True)
    shop_name = models.CharField(max_length=256, null=True, blank=True)
    shop_address = models.CharField(max_length=256, null=True, blank=True)
    shop_exp_price = models.CharField(max_length=256, null=True, blank=True)
    shop_item_description = models.TextField()
    shop_item_quantity = models.CharField(max_length=256, null=True, blank=True)
    transaction = models.ForeignKey(Transaction)


class OrderTrans(BaseModel):
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=256, null=True, blank=True)
    card_num = models.PositiveIntegerField()
    card_cvc = models.PositiveIntegerField()
    card_exp_month = models.PositiveIntegerField()
    card_exp_year = models.PositiveIntegerField()
    item_name = models.CharField(max_length=256, null=True, blank=True)
    item_number = models.CharField(max_length=50, null=True, blank=True)
    item_price = models.FloatField(default=0)
    item_price_currency = models.CharField(max_length=10, null=True, blank=True) #  DEFAULT 'usd',
    paid_amount = models.FloatField(default=0)
    paid_amount_currency = models.CharField(max_length=10, null=True, blank=True) #  DEFAULT 'usd',
    txn_id = models.CharField(max_length=100, null=True, blank=True)
    payment_status = models.CharField(max_length=50, null=True, blank=True)


class OrderDeliveryStatus(BaseModel):
    order = models.ForeignKey(Order)
    user = models.ForeignKey(User)
    status = models.PositiveSmallIntegerField(choices=) # DEFAULT '1' COMMENT '1=pending,2=deleivered,3=canceled',
    comment = models.TextField()


class OrderProduct(BaseModel):
    order = models.ForeignKey(Order)
    product = models.ForeignKey(Product)
    quantity = models.PositiveIntegerField(default=0)
    title = models.CharField(max_length=100, null=True, blank=True)
    image = models.CharField(max_length=100, null=True, blank=True)
    price = models.CharField(max_length=100, null=True, blank=True)
    colour = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    status = models.PositiveSmallIntegerField(choices=) # enum('Active','Inactive','Deleted','') NOT NULL DEFAULT 'Active',
